"""Verify the supported binary before generating the plugin compatibility gate."""
import argparse
import hashlib
import importlib.util
import json
import struct
from pathlib import Path

import capstone

spec = importlib.util.spec_from_file_location('inspect_loading', Path(__file__).with_name('inspect-loading.py'))
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--game', default=r'E:\SteamLibrary\steamapps\common\Kenshi')
args = parser.parse_args()
engine = module.Engine(args.game)
root = Path(__file__).resolve().parent.parent
expected_hash = '504b362cde850d56afb1cea6f5b7b0ee014d9dd7b47e188599d91c804502cd3e'
actual_hash = hashlib.sha256(engine.path.read_bytes()).hexdigest()
assert actual_hash == expected_hash, 'Unsupported executable: reinspect loading behavior before adding support'

def code(part, size):
    return engine.code(engine.address(part), size)

def calls(instructions):
    return [engine.follow(i.operands[0].imm) for i in instructions
            if i.mnemonic in ('call', 'jmp') and i.operands[0].type == capstone.x86.X86_OP_IMM]

def contains(instructions, mnemonic, operands):
    return any(i.mnemonic == mnemonic and i.op_str == operands for i in instructions)

process = code('processLoading@ZoneManager', 0x5f1)
phase1 = code('loadPhase1@ZoneManager', 0xa4)
phase2 = code('loadPhase2@ZoneManager', 0x33e)
phase3 = code('loadPhase3@ZoneManager', 0x55b)
activate = code('activateZoneMap@ZoneManager@@QEAA_NPEAVZoneMap', 0x250)
zone_activate = code('_activate@ZoneMap@@', 0x181)
assert contains(process, 'cmp', 'byte ptr [rdx + 0xb1], 0'), 'Native loaded-state pause predicate changed'
assert contains(process, 'mov', 'dl, 1')
assert engine.address('togglePause@GameWorld') in calls(process)
assert engine.address('loadPhase1@ZoneManager') in calls(process)
assert engine.address('loadPhase2@ZoneManager') in calls(process)
assert engine.address('loadPhase3@ZoneManager') in calls(process)
assert engine.address('isLoaded@NavMesh@@QEAA_NPEAVZoneMap') in calls(process)
assert engine.address('queuesAreClearMT@PhysicsInterface') in calls(phase3)
assert engine.address('create@NavMesh@@QEAA') in calls(phase3)
assert contains(phase1, 'cmp', 'qword ptr [rbx + 0x1680e8], 0'), 'Pending work admission changed'
assert contains(phase2, 'mov', 'dword ptr [r13 + 0x1681d8], 3'), 'Phase progression changed'
assert contains(activate, 'lea', 'rcx, [r12 + 0x1680c8]'), 'Manager must register pending zones'
assert contains(zone_activate, 'movss', 'dword ptr [rsi + rbx*4 + 0xc0], xmm6'), 'Lease layout changed'
assert contains(code('isLoadedMT@ZoneMap', 16), 'movzx', 'eax, byte ptr [rcx + 0xb1]')
assert contains(code('isBeingLoadedMT@ZoneMap', 16), 'movzx', 'eax, byte ptr [rcx + 0xb0]')
assert contains(code('getZoneMap@ZoneManager@@QEAAPEAVZoneMap@@HH', 0x40), 'imul', 'rdx, rdx, 0x168')
sector_code = code('getSubMapSector@UtilityT', 0x6c)
constants = []
for ins in sector_code:
    if ins.mnemonic in ('movss', 'mulss'):
        for op in ins.operands:
            if op.type == capstone.x86.X86_OP_MEM and op.mem.base == capstone.x86.X86_REG_RIP:
                constants.append(struct.unpack('<f', engine.pe.get_data(ins.address + ins.size + op.mem.disp, 4))[0])
assert constants == [4608.0, 32.0, 4608.0, 32.0], 'Grid conversion changed'
assert contains(code('togglePause@GameWorld', 0xf8), 'or', 'bl, al'), 'User pause preservation changed'
assert engine.address('resetGame@GameWorld') in calls(code('loadGame@SaveManager', 0x100))
assert engine.address('resetGame@GameWorld') in calls(code('importGame@SaveManager', 0x120))

symbols = {
    'Update': 'updateMainThread@ZoneManager',
    'Reset': '_clearAndDestroyGameWorldStuff@GameWorld',
    'GameReset': 'resetGame@GameWorld',
    'Activate': 'activateZoneMap@ZoneManager@@QEAA_NPEAVZoneMap',
    'Process': 'processLoading@ZoneManager',
}
addresses = {name: engine.address(part) for name, part in symbols.items()}
header = '// Generated by tools/verify-native.py after installed-binary verification.\n#pragma once\n'
header += 'static const unsigned char NativeEngineSHA256[32] = {'
header += ','.join('0x' + expected_hash[i:i+2] for i in range(0, 64, 2)) + '};\n'
for name, address in addresses.items():
    header += f'static const unsigned int Native{name}RVA = 0x{address:x};\n'
(root / 'plugin').mkdir(exist_ok=True)
(root / 'plugin/NativeContract.h').write_text(header, encoding='ascii')
(root / 'build').mkdir(exist_ok=True)
report = {
    'result': 'PASS', 'engine': str(engine.path), 'engine_sha256': actual_hash,
    'kenshilib_sha256': hashlib.sha256((engine.game / 'KenshiLib.dll').read_bytes()).hexdigest(),
    'rva_sha256': hashlib.sha256(engine.rvas).hexdigest(),
    'addresses': {name: hex(address) for name, address in addresses.items()},
    'verified': ['camera loaded-state pause guard', 'native pending-set admission',
                 'phase progression', 'physics/navmesh barriers', 'activation countdown layout',
                 'loaded-state accessors', 'grid layout and conversion', 'user pause preserved',
                 'normal save-load and import reset boundary'],
    'runtime_tested': False,
}
(root / 'build/native-contract.json').write_text(json.dumps(report, indent=2) + '\n', encoding='ascii')
print('NATIVE CONTRACT: PASS; generated plugin/NativeContract.h and build/native-contract.json')
